runtime: aspnetcore
env: standard

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

env_variables:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://*:8080

# Para archivos estáticos grandes
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?tests$
- ^(.*/)?test$
- node_modules/