steps:
# Restaurar paquetes NuGet
- name: 'mcr.microsoft.com/dotnet/sdk:8.0'
  args: ['dotnet', 'restore']

# Compilar el proyecto
- name: 'mcr.microsoft.com/dotnet/sdk:8.0'
  args: ['dotnet', 'build', '--configuration', 'Release']

# Publicar el proyecto
- name: 'mcr.microsoft.com/dotnet/sdk:8.0'
  args: ['dotnet', 'publish', '--configuration', 'Release', '--output', '/workspace/publish']

# Construir la imagen Docker
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ccc-rugby-web:$COMMIT_SHA', '.']

# Publicar la imagen en Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/ccc-rugby-web:$COMMIT_SHA']

# Desplegar en Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'ccc-rugby-web'
  - '--image'
  - 'gcr.io/$PROJECT_ID/ccc-rugby-web:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'

images:
- 'gcr.io/$PROJECT_ID/ccc-rugby-web:$COMMIT_SHA'
