// <auto-generated />
using System;
using CCC_Rugby_Web.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CCC_Rugby_Web.Migrations
{
    [DbContext(typeof(CCC_DbContext))]
    [Migration("20250812012405_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CCC_Rugby_Web.Models.Entityes.Archivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BorradoLogico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("borrado_logico")
                        .HasColumnOrder(999);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasColumnOrder(993);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by")
                        .HasColumnOrder(994);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at")
                        .HasColumnOrder(997);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int")
                        .HasColumnName("deleted_by")
                        .HasColumnOrder(998);

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("extension")
                        .HasColumnOrder(3);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre")
                        .HasColumnOrder(1);

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type")
                        .HasColumnOrder(2);

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(995);

                    b.Property<int?>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("updated_by")
                        .HasColumnOrder(996);

                    b.Property<byte[]>("bytes")
                        .IsRequired()
                        .HasColumnType("blob")
                        .HasColumnName("base64")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("archivo");
                });

            modelBuilder.Entity("CCC_Rugby_Web.Models.Entityes.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BorradoLogico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("borrado_logico")
                        .HasColumnOrder(999);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasColumnOrder(993);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by")
                        .HasColumnOrder(994);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at")
                        .HasColumnOrder(997);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int")
                        .HasColumnName("deleted_by")
                        .HasColumnOrder(998);

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(995);

                    b.Property<int?>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("updated_by")
                        .HasColumnOrder(996);

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("menu");
                });

            modelBuilder.Entity("CCC_Rugby_Web.Models.Entityes.MenuGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BorradoLogico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("borrado_logico")
                        .HasColumnOrder(999);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasColumnOrder(993);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by")
                        .HasColumnOrder(994);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at")
                        .HasColumnOrder(997);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int")
                        .HasColumnName("deleted_by")
                        .HasColumnOrder(998);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion")
                        .HasColumnOrder(2);

                    b.Property<int>("MenuId")
                        .HasColumnType("int")
                        .HasColumnName("menu_id")
                        .HasColumnOrder(3);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre")
                        .HasColumnOrder(1);

                    b.Property<int?>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id")
                        .HasColumnOrder(4);

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(995);

                    b.Property<int?>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("updated_by")
                        .HasColumnOrder(996);

                    b.Property<string>("_icono")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("<path d=\"M0 0h24v24H0z\" fill=\"none\"/><path d=\"M3 13h2v-2H3v2zm0 4h2v-2H3v2zm0-8h2V7H3v2zm4 4h14v-2H7v2zm0 4h14v-2H7v2zM7 7v2h14V7H7z\"/>")
                        .HasColumnName("icono")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("MenuId");

                    b.HasIndex("RolId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("menu_grupo");
                });

            modelBuilder.Entity("CCC_Rugby_Web.Models.Entityes.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BorradoLogico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("borrado_logico")
                        .HasColumnOrder(999);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("codigo")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasColumnOrder(993);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by")
                        .HasColumnOrder(994);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at")
                        .HasColumnOrder(997);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int")
                        .HasColumnName("deleted_by")
                        .HasColumnOrder(998);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion")
                        .HasColumnOrder(2);

                    b.Property<int>("MenuGrupoId")
                        .HasColumnType("int")
                        .HasColumnName("menu_grupo_id")
                        .HasColumnOrder(5);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(995);

                    b.Property<int?>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("updated_by")
                        .HasColumnOrder(996);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("url")
                        .HasColumnOrder(4);

                    b.Property<string>("_icono")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("<path d=\"M0 0h24v24H0z\" fill=\"none\"/><path d=\"M3 13h2v-2H3v2zm0 4h2v-2H3v2zm0-8h2V7H3v2zm4 4h14v-2H7v2zm0 4h14v-2H7v2zM7 7v2h14V7H7z\"/>")
                        .HasColumnName("icono")
                        .HasColumnOrder(6);

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("MenuGrupoId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("menu_item");
                });

            modelBuilder.Entity("CCC_Rugby_Web.Models.Entityes.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BorradoLogico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("borrado_logico")
                        .HasColumnOrder(999);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasColumnOrder(993);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by")
                        .HasColumnOrder(994);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at")
                        .HasColumnOrder(997);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int")
                        .HasColumnName("deleted_by")
                        .HasColumnOrder(998);

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(995);

                    b.Property<int?>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("updated_by")
                        .HasColumnOrder(996);

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("permiso");
                });

            modelBuilder.Entity("CCC_Rugby_Web.Models.Entityes.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("apellidos");

                    b.Property<bool>("BorradoLogico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("borrado_logico")
                        .HasColumnOrder(999);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasColumnOrder(993);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by")
                        .HasColumnOrder(994);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at")
                        .HasColumnOrder(997);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int")
                        .HasColumnName("deleted_by")
                        .HasColumnOrder(998);

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("documento");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("genero");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombres");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tipo_documento");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(995);

                    b.Property<int?>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("updated_by")
                        .HasColumnOrder(996);

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("TipoDocumento", "Documento")
                        .IsUnique();

                    b.ToTable("persona");
                });

            modelBuilder.Entity("CCC_Rugby_Web.Models.Entityes.RolPermiso", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.Property<int>("PermisoId")
                        .HasColumnType("int")
                        .HasColumnName("permiso_id");

                    b.HasKey("RolId");

                    b.HasIndex("PermisoId");

                    b.ToTable("rol_permiso");
                });

            modelBuilder.Entity("CCC_Rugby_Web.Models.Entityes.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BorradoLogico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("borrado_logico")
                        .HasColumnOrder(999);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("codigo")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasColumnOrder(993);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by")
                        .HasColumnOrder(994);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at")
                        .HasColumnOrder(997);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int")
                        .HasColumnName("deleted_by")
                        .HasColumnOrder(998);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("descripcion")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(995);

                    b.Property<int?>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("updated_by")
                        .HasColumnOrder(996);

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("rol");
                });

            modelBuilder.Entity("CCC_Rugby_Web.Models.Entityes.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvatarArchivoId")
                        .HasColumnType("int")
                        .HasColumnName("avatar_archivo_id")
                        .HasColumnOrder(5);

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("bloqueado")
                        .HasColumnOrder(8);

                    b.Property<bool>("BorradoLogico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("borrado_logico")
                        .HasColumnOrder(999);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at")
                        .HasColumnOrder(997);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int")
                        .HasColumnName("deleted_by")
                        .HasColumnOrder(998);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email")
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("LastLogin")
                        .IsRequired()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login")
                        .HasColumnOrder(6);

                    b.Property<int>("LoginTrys")
                        .HasColumnType("int")
                        .HasColumnName("login_trys")
                        .HasColumnOrder(7);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password")
                        .HasColumnOrder(2);

                    b.Property<int?>("PersonaId")
                        .HasColumnType("int")
                        .HasColumnName("persona_id")
                        .HasColumnOrder(4);

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(995);

                    b.Property<int?>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("updated_by")
                        .HasColumnOrder(996);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("username")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("AvatarArchivoId");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("PersonaId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("CCC_Rugby_Web.Models.Entityes.UsuarioRol", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId");

                    b.HasIndex("RoleId");

                    b.ToTable("usuario_rol");
                });

            modelBuilder.Entity("CCC_Rugby_Web.Models.Entityes.Archivo", b =>
                {
                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Usuario", "CreatedByUsuario")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Usuario", "DeletedByUsuario")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Usuario", "UpdatedByUsuario")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUsuario");

                    b.Navigation("DeletedByUsuario");

                    b.Navigation("UpdatedByUsuario");
                });

            modelBuilder.Entity("CCC_Rugby_Web.Models.Entityes.Menu", b =>
                {
                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Usuario", "CreatedByUsuario")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Usuario", "DeletedByUsuario")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Usuario", "UpdatedByUsuario")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUsuario");

                    b.Navigation("DeletedByUsuario");

                    b.Navigation("UpdatedByUsuario");
                });

            modelBuilder.Entity("CCC_Rugby_Web.Models.Entityes.MenuGroup", b =>
                {
                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Usuario", "CreatedByUsuario")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Usuario", "DeletedByUsuario")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Role", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId");

                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Usuario", "UpdatedByUsuario")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUsuario");

                    b.Navigation("DeletedByUsuario");

                    b.Navigation("Menu");

                    b.Navigation("Rol");

                    b.Navigation("UpdatedByUsuario");
                });

            modelBuilder.Entity("CCC_Rugby_Web.Models.Entityes.MenuItem", b =>
                {
                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Usuario", "CreatedByUsuario")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Usuario", "DeletedByUsuario")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CCC_Rugby_Web.Models.Entityes.MenuGroup", "MenuGrupo")
                        .WithMany()
                        .HasForeignKey("MenuGrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Usuario", "UpdatedByUsuario")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUsuario");

                    b.Navigation("DeletedByUsuario");

                    b.Navigation("MenuGrupo");

                    b.Navigation("UpdatedByUsuario");
                });

            modelBuilder.Entity("CCC_Rugby_Web.Models.Entityes.Permiso", b =>
                {
                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Usuario", "CreatedByUsuario")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Usuario", "DeletedByUsuario")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Usuario", "UpdatedByUsuario")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUsuario");

                    b.Navigation("DeletedByUsuario");

                    b.Navigation("UpdatedByUsuario");
                });

            modelBuilder.Entity("CCC_Rugby_Web.Models.Entityes.Persona", b =>
                {
                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Usuario", "CreatedByUsuario")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Usuario", "DeletedByUsuario")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Usuario", "UpdatedByUsuario")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUsuario");

                    b.Navigation("DeletedByUsuario");

                    b.Navigation("UpdatedByUsuario");
                });

            modelBuilder.Entity("CCC_Rugby_Web.Models.Entityes.RolPermiso", b =>
                {
                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Permiso", "Permiso")
                        .WithMany()
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Role", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("CCC_Rugby_Web.Models.Entityes.Role", b =>
                {
                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Usuario", "CreatedByUsuario")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Usuario", "DeletedByUsuario")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Usuario", "UpdatedByUsuario")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUsuario");

                    b.Navigation("DeletedByUsuario");

                    b.Navigation("UpdatedByUsuario");
                });

            modelBuilder.Entity("CCC_Rugby_Web.Models.Entityes.Usuario", b =>
                {
                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Archivo", "AvatarArchivo")
                        .WithMany()
                        .HasForeignKey("AvatarArchivoId");

                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Usuario", "DeletedByUsuario")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId");

                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Usuario", "UpdatedByUsuario")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AvatarArchivo");

                    b.Navigation("DeletedByUsuario");

                    b.Navigation("Persona");

                    b.Navigation("UpdatedByUsuario");
                });

            modelBuilder.Entity("CCC_Rugby_Web.Models.Entityes.UsuarioRol", b =>
                {
                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CCC_Rugby_Web.Models.Entityes.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
